-- =================================================================
-- TASK 2: Generating New Data by Energy Type
-- Project : Intel Data Center Location Analysis
-- Author  : Sai Krishna Varshith Danda
-- Goal    : Build a combined dataset that separates renewable
--           energy from fossil fuel energy over time
-- =================================================================


-- -----------------------------------------------------------------
-- TASK 2A: Daily Renewable Energy Generated by Region
-- -----------------------------------------------------------------
-- WHY: To analyze how renewable energy trends over time, we first
--      need to isolate it from the rest of the energy mix.

SELECT
    date,
    region,
    SUM(hydropower_and_pumped_storage + wind + solar) AS energy_generated_mw
FROM intel.energy_data
GROUP BY date, region;


-- -----------------------------------------------------------------
-- TASK 2B: Adding Energy Type Label - Renewable Energy
-- -----------------------------------------------------------------
-- WHY: Adding a static label makes filtering and visualization
--      much easier in Tableau.

SELECT
    date,
    region,
    SUM(hydropower_and_pumped_storage + wind + solar) AS energy_generated_mw,
    'renewable energy' AS energy_type
FROM intel.energy_data
GROUP BY date, region;


-- -----------------------------------------------------------------
-- TASK 2C: Daily Fossil Fuel Energy Generated by Region
-- -----------------------------------------------------------------
-- WHY: To compare fossil fuel trends against renewable trends.

SELECT
    date,
    region,
    SUM(
        all_petroleum_products + coal + natural_gas + nuclear + other_fuel_sources
    ) AS energy_generated_mw
FROM intel.energy_data
GROUP BY date, region;


-- -----------------------------------------------------------------
-- TASK 2D: Adding Energy Type Label - Fossil Fuel
-- -----------------------------------------------------------------

SELECT
    date,
    region,
    SUM(
        all_petroleum_products + coal + natural_gas + nuclear + other_fuel_sources
    ) AS energy_generated_mw,
    'fossil fuel' AS energy_type
FROM intel.energy_data
GROUP BY date, region;


-- -----------------------------------------------------------------
-- TASK 2E: Final Combined Dataset - Renewable + Fossil Fuel
-- -----------------------------------------------------------------
-- WHY: Using UNION ALL we stack both energy type tables into one
--      clean table. This structure allows Tableau to easily plot
--      both energy types on the same chart.

SELECT
    date,
    region,
    SUM(hydropower_and_pumped_storage + wind + solar) AS energy_generated_mw,
    'renewable energy' AS energy_type
FROM intel.energy_data
GROUP BY date, region

UNION ALL

SELECT
    date,
    region,
    SUM(
        all_petroleum_products + coal + natural_gas + nuclear + other_fuel_sources
    ) AS energy_generated_mw,
    'fossil fuel' AS energy_type
FROM intel.energy_data
GROUP BY date, region;

-- FINDING: Fossil fuel generation still dominates most regions
--          but renewable energy is growing steadily, especially
--          in the Northwest and California.
